name: PR Agent

on:
  pull_request:
    types: [opened, reopened, synchronize]
  issue_comment:
    types: [created, edited]

jobs:
  pr_agent_job:
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: Run PR Agent
    steps:
      - id: pr-agent
        uses: Codium-ai/pr-agent@main
        env:
          DEEPSEEK.KEY: ${{ secrets.DEEPSEEK_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          github_action_config.auto_review: "true"
          github_action_config.auto_describe: "true"
          github_action_config.auto_improve: "true"
          CONFIG.MODEL: "deepseek/deepseek-chat"
          CONFIG.FALLBACK_MODELS: '["deepseek/deepseek-chat"]'
